<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YyOfSkAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yyOfSkA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yyOfSkA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'historique' => ['privates', '.errored..service_locator.yyOfSkA.App\\Entity\\Historique', NULL, 'Cannot autowire service ".service_locator.yyOfSkA": it needs an instance of "App\\Entity\\Historique" but this type has been excluded in "config/services.yaml".'],
        ], [
            'historique' => 'App\\Entity\\Historique',
        ]);
    }
}
