<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EZ8U3w0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eZ8U3w0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eZ8U3w0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appContact' => ['privates', '.errored..service_locator.eZ8U3w0.App\\Entity\\AppContact', NULL, 'Cannot autowire service ".service_locator.eZ8U3w0": it needs an instance of "App\\Entity\\AppContact" but this type has been excluded in "config/services.yaml".'],
        ], [
            'appContact' => 'App\\Entity\\AppContact',
        ]);
    }
}
