<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FwGxqNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FwGxq_n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FwGxq_n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'oldPost' => ['privates', '.errored..service_locator.FwGxq_n.App\\Entity\\OldPost', NULL, 'Cannot autowire service ".service_locator.FwGxq_n": it needs an instance of "App\\Entity\\OldPost" but this type has been excluded in "config/services.yaml".'],
        ], [
            'oldPost' => 'App\\Entity\\OldPost',
        ]);
    }
}
