<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M3dBI7nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M3dBI7n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M3dBI7n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'profile' => ['privates', '.errored..service_locator.M3dBI7n.App\\Entity\\Profile', NULL, 'Cannot autowire service ".service_locator.M3dBI7n": it needs an instance of "App\\Entity\\Profile" but this type has been excluded in "config/services.yaml".'],
        ], [
            'profile' => 'App\\Entity\\Profile',
        ]);
    }
}
