<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FTrb1elService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fTrb1el' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fTrb1el'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appFAQ' => ['privates', '.errored..service_locator.fTrb1el.App\\Entity\\AppFAQ', NULL, 'Cannot autowire service ".service_locator.fTrb1el": it needs an instance of "App\\Entity\\AppFAQ" but this type has been excluded in "config/services.yaml".'],
        ], [
            'appFAQ' => 'App\\Entity\\AppFAQ',
        ]);
    }
}
