<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppFAQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fTrb1el.App\Entity\AppFAQ' shared service.
     *
     * @return \App\Entity\AppFAQ
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fTrb1el": it needs an instance of "App\\Entity\\AppFAQ" but this type has been excluded in "config/services.yaml".');
    }
}
