<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppContactService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eZ8U3w0.App\Entity\AppContact' shared service.
     *
     * @return \App\Entity\AppContact
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eZ8U3w0": it needs an instance of "App\\Entity\\AppContact" but this type has been excluded in "config/services.yaml".');
    }
}
