<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogPostFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\BlogPostFormType' shared autowired service.
     *
     * @return \App\Form\BlogPostFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/BlogPostFormType.php';

        return $container->privates['App\\Form\\BlogPostFormType'] = new \App\Form\BlogPostFormType(($container->privates['security.helper'] ?? $container->getSecurity_HelperService()));
    }
}
