<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BlogController' shared autowired service.
     *
     * @return \App\Controller\BlogController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BlogController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/UploadHelper.php';

        $container->services['App\\Controller\\BlogController'] = $instance = new \App\Controller\BlogController(($container->privates['App\\Repository\\BlogPostRepository'] ?? $container->load('getBlogPostRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\HistoriqueRepository'] ?? $container->load('getHistoriqueRepositoryService')), new \App\Services\UploadHelper((\dirname(__DIR__, 4).'/public/images')));

        $instance->setContainer(($container->privates['.service_locator.2h6BSJb'] ?? $container->load('get_ServiceLocator_2h6BSJbService'))->withContext('App\\Controller\\BlogController', $container));

        return $instance;
    }
}
