<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiipImagine_Templating_FilterRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'liip_imagine.templating.filter_runtime' shared service.
     *
     * @return \Liip\ImagineBundle\Templating\LazyFilterRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Templating/LazyFilterRuntime.php';

        $a = ($container->services['liip_imagine.cache.manager'] ?? $container->load('getLiipImagine_Cache_ManagerService'));

        if (isset($container->privates['liip_imagine.templating.filter_runtime'])) {
            return $container->privates['liip_imagine.templating.filter_runtime'];
        }

        return $container->privates['liip_imagine.templating.filter_runtime'] = new \Liip\ImagineBundle\Templating\LazyFilterRuntime($a, NULL);
    }
}
