<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOldPostService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FwGxq_n.App\Entity\OldPost' shared service.
     *
     * @return \App\Entity\OldPost
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FwGxq_n": it needs an instance of "App\\Entity\\OldPost" but this type has been excluded in "config/services.yaml".');
    }
}
