<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOldPostFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\OldPostFormType' shared autowired service.
     *
     * @return \App\Form\OldPostFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/OldPostFormType.php';

        return $container->privates['App\\Form\\OldPostFormType'] = new \App\Form\OldPostFormType();
    }
}
