<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.M3dBI7n.App\Entity\Profile' shared service.
     *
     * @return \App\Entity\Profile
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.M3dBI7n": it needs an instance of "App\\Entity\\Profile" but this type has been excluded in "config/services.yaml".');
    }
}
