<?php

namespace ContainerE2mBiGA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParamsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ParamsController' shared autowired service.
     *
     * @return \App\Controller\ParamsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ParamsController.php';

        $container->services['App\\Controller\\ParamsController'] = $instance = new \App\Controller\ParamsController(($container->privates['App\\Repository\\ParamsRepository'] ?? $container->load('getParamsRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.2h6BSJb'] ?? $container->load('get_ServiceLocator_2h6BSJbService'))->withContext('App\\Controller\\ParamsController', $container));

        return $instance;
    }
}
